### ISSUE TITLE
Grammar issue

### ISSUE THREAD

**Issue by Pequla** [LukeOnuke/microhud#1]
Missing . at the end of year
![image](https://user-images.githubusercontent.com/58506649/176987465-88e90e67-148b-4dca-a924-7ed08580b114.png)

Suggestion: Maybe use dashes inbetween the dates instead of dots. That way its more readable and is eazier for later mutli date format implementation
Ex: **02-07-2022**

**Comment by LukeOnuke** [comment]
fixed
