### ISSUE TITLE
microhud position is weirding out when swapping gamemodes

### ISSUE THREAD

**Issue by Rifteny** [LukeOnuke/microhud#3]
i was playing mc 1.20.1 on quilt 0.23.0-beta.1 and noticed that when you change the gamemode from creative to survival microhud weirdly adjusts to the centre and becomes much smaller
deleting the json file in the instance folder didn't help at all and i can't seem to 100% redo the bug, it appears out of nowhere
![image](https://github.com/LukeOnuke/microhud/assets/155186430/9eacd752-7c18-4c5e-95aa-504a0e9ea0a9)
![image](https://github.com/LukeOnuke/microhud/assets/155186430/5b031ad2-8f82-4d79-b62a-a6ed4eef115f)

**Comment by LukeOnuke** [comment]
Was away for a bit, will look into it now.
Whats your os and are you using the default jdk?

**Comment by Rifteny** [comment]
Win10 64-bit, I don't quite get what you mean by default jdk, but I use the one from the official oracle website. Also, one strange thing, number of mods affects this, for example I have 277 mods and I'm in survival = everything's fine, if I have 278 mods and I'm in survival, this glitch happens. It's also the other way around, if I have 277 mods and I'm in creative = the glitch happens, you get the other thing...

**Comment by LukeOnuke** [comment]
Allright.
Are you maybe removing a specific mod every time?

**Comment by Rifteny** [comment]
No, only the mod count and gamemode affects this

**Comment by LukeOnuke** [comment]
Interesting, looking at the renderer code there is nothing that changes on my side that would cause the x position to change.
In the line renderer render method ( `MicroHudRenderer.java#render()` )
https://github.com/LukeOnuke/microhud/blob/884bc5034062a33afe2728f4460909f57a862252/src/main/java/com/lukeonuke/minihud/renderer/MicroHudRenderer.java#L79-L94

The specific line that draws it to the screen is 
https://github.com/LukeOnuke/microhud/blob/884bc5034062a33afe2728f4460909f57a862252/src/main/java/com/lukeonuke/minihud/renderer/MicroHudRenderer.java#L88

So the only thing that i could think of that could cause this is some mod messing with the screen width property.

Are you using custom gui mods or something like widescreen gui?

**Comment by Rifteny** [comment]
I don't really remember putting any gui mods besides microhud; if I send you the modlist, would you be able to identify one?

**Comment by LukeOnuke** [comment]
I can try

**Comment by Rifteny** [comment]
[modpack.zip](https://github.com/LukeOnuke/microhud/files/14022715/modpack.zip)

**Comment by LukeOnuke** [comment]
I have absolutly no idea whats causing this.

Ive tripplechecked everything, even had my friends look at it to check if im insane, nah it seems its some other mod that messes with the variable. Maybe even quit?

**Comment by Rifteny** [comment]
Considering this mod was made for fabric, it's probably quilt being silly in this situation.
