### ISSUE TITLE
Crashing on 1.20.6

### ISSUE THREAD

**Issue by lazykoid** [LukeOnuke/microhud#5]
Crashing when trying to load in to 1.20.6
[crash-2024-06-12_18.58.00-client.txt](https://github.com/user-attachments/files/15811386/crash-2024-06-12_18.58.00-client.txt)

**Comment by LukeOnuke** [comment]
Hm how did i not get a notification for this

**Comment by LukeOnuke** [comment]
Thanks for reporting, ill need to get it ported to 1.21. Might not port it to 1.20.6

**Comment by LukeOnuke** [comment]
well currently serving my country, im working on it but its gonna take a bit

**Comment by LukeOnuke** [comment]
dont think i forgot, just life is realy uh happening recently lmao

**Comment by LukeOnuke** [comment]
Alpha ported to 1.21.3. Bit buggy rn but will get fixed
